### PR TITLE
New location node

### PR DESCRIPTION
**Pull request by danTapps**
The events PR should be looked at first

### CODE REVIEW

**Comment by fblackburn1** [comment]
Do you have other example of location events? (other than systemStart?) Or documentation about location events?
I'm trying to figure out what is this kind of node
Do you know a REST API endpoint to know *all location attributes*?

---

Do you know how many event types there are in HE? My first idea to solve this kind of problems (retrieve events there are not device or mode) was to make a generic node that receive all undetermined events. While I like the idea to have a specific node for each event type, I'm trying to know and order of magnitude ( 100 vs 10 event types)?

**Comment by danTapps** [comment]
Sunrise, sunset are two more examples.

**Comment by danTapps** [comment]
And there is no REST endpoint as you can’t trigger location events remotely

**Comment by fblackburn1** [comment]
In your original PR you wrote
```
       } else if (req.body.content.deviceId === null) {
          node.hubitatEvent.emit('location', req.body.content);
        }
```
But this check get all events not caught by other conditions. If other HE application trigger other events, then it will be in the `location` node. Which is not what we want (ex: hsmSetAlarm). I see two solution for this:
* list all possible name values for location events
* transform the location node to a generic one and receive all events not handled by other nodes

**Comment by danTapps** [comment]
the hsmSetAlarm would not be triggering as it starts with hsm and the
previous condition checks if the event name starts with hsm...

But yes, that is the definition of location events, these are events that
are not associate with a device, as in deviceId == null.
I only filtered out the hsm events as I wanted to have an individual node
for HSM

**Comment by danTapps** [comment]
Something might have gotten lost when I split up the PRs. Here is how I had
it intended in the config.js

        if (req.body.content.deviceId != null) {
          node.hubitatEvent.emit('device', req.body.content);
        } else if (req.body.content.name === 'mode') {
          node.hubitatEvent.emit('mode', req.body.content);
        } else if (req.body.content.name.startsWith('hsm')) {
          if ((req.body.content.name === 'hsmStatus') || (
req.body.content.name === 'hsmAlert') || (req.body.content.name ===
'hsmRules'))
            node.hubitatEvent.emit('hsm', req.body.content);
        } else if (req.body.content.deviceId === null) {
          node.hubitatEvent.emit('location', req.body.content);
        }

**Comment by fblackburn1** [comment]
> the hsmSetAlarm would not be triggering as it starts with hsm and the previous condition checks if the event name starts with hsm... 

true, I've not seen the `startsWith` condition

> But yes, that is the definition of location events, these are events that are not associate with a device, as in deviceId == null.

My comment remains the same, if there are other applications with events that have deviceId === null and are not related to location. I don't have other example since I don't really use HE applications, but I will trust you on it and if it cause issues, we will think of alternative solution :)

It's not only the missing REST API documentation which is annoying, the missing events documentation too...

**Pull request merged**
