### PR TITLE
use events instead of callbacks to avoid fake deviceIDs 

### PR DESCRIPTION
**Pull request by danTapps**
This is the base and should be looked at first as the other PRs will rely on it

### CODE REVIEW

**Comment by fblackburn1** [comment]
Really nice improvement !! :+1: 
It was a subject on which I saw coming and you just solve it perfectly :smile:

**Comment by fblackburn1** [comment]
> You can't use the "this" in the event handler, that will break it. You have to use the "node" within the event handler! The "this" belongs to the parent event handler, that is why the "this" get's bind to "node"

Maybe I don't understand your comment, but it's the reason I have use "node" instead of "this" in the commit.
Do you say that replacing "this" by "node" is wrong?

**Comment by danTapps** [comment]
Never mind, I read the commit the other way around. You have it right....

**Comment by fblackburn1** [comment]
> Never mind, I read the commit the other way around. You have it right....

no problem, but my message commit was really confusing, so I rewrote it
I will continue to work on this branch tomorrow

**Pull request merged**
