### PR TITLE
Global cache

### PR DESCRIPTION
**Pull request by fblackburn1**
Ready to be merged

### manual tests

Scenarios that should be tested manually before merging this branch

1. deploy device node, new device HE, deploy config node
    * OK: Cache is built on deploy
2. deploy device node, old device HE, without redeploy config node
    * OK: deploying device node will redeploy config node automatically
3. deploy device node, old device HE, deploy config node
    * OK: Same as 1
4. deploy device node, new device HE, without redeploy config node
    * OK: It will be initialized like other nodes
5. redeploy other nodes, without redeploy config and device node
    * OK
6. deploy config node, without redeploy device node
    * OK: if config node is redeployed, then all related nodes will be redeployed too

7. missing HE events
    * OK: on the next event received, the state will be restored

### Note
All device nodes related to a configuration node will be redeployed even if you only deploy `Modified Nodes` when you will update one of these node (ex: if you have config node A and device node B & C, then if you update only node C and deploy modified flow, then node A-B-C will be deployed). That's because the config node related to the modified node will be mark as dirty and will dirt all related nodes.
This behavior seems only related to device node (not other nodes)

### CODE REVIEW

**Comment by fblackburn1** [comment]
Scenarios that should be tested manually before merging this branch (I'll update this post with OK/NOK when it will be done). 

1. deploy device node, new device HE, deploy config node
  * OK/NOK: Cache is built on deploy
2. deploy device node, old device HE, without redeploy config node
  * OK/NOK: Already in the cache (because other same device node exists)
  * OK/NOK: Not in the cache, then it will be initialized like other nodes
3. deploy device node, old device HE, deploy config node
  * OK/NOK: Same as 1
4. deploy device node, new device HE, without redeploy config node
  * OK/NOK: It will be initialized like other nodes
5. redeploy other nodes, without redeploy config and device node
  * OK/NOK
6. deploy config node, without redeploy device node
  * OK/NOK: On the next device node read, the node will be reinitialized

**Comment by fblackburn1** [comment]
@Botched1 If you want to test it :angel:

**Comment by Botched1** [comment]
Will do! I just have to figure out how to install it manually. You remember how poorly that went for me last time. LOL

**Comment by fblackburn1** [comment]
> Will do! I just have to figure out how to install it manually. You remember how poorly that went for me last time. LOL

```
git clone https://github.com/danTapps/node-red-contrib-hubitat.git /tmp/nr-he
cd /tmp/nr-he
git checkout global-cache
docker run --name nodered-hubitat --rm -v /tmp/nr-he:/tmp/nr-he -d -p 1880:1880 nodered/node-red
docker exec -it nodered-hubitat bash
  npm install /tmp/nr-he
docker restart nodered-hubitat
```

**Comment by Botched1** [comment]
No worries, I'll try it in a few hours when I get home.

**Comment by Botched1** [comment]
OK. I believe I have ti all installed now. Any way I can confirm I'm on the right version (it still says 1.2.1 in the palette of course)?

Any specific tests you would like done? If not, I'll just try to set it up how I would normally use it.

**Comment by fblackburn1** [comment]
> Is there any way I can confirm I'm on the right version (it still says 1.2.1 in the palette of course, but that is likely expected)?

Good question ! You need to change the logger to debug and look at the log. Add many nodes of the same devices. On deploy:
* if you have old version: you will see one request log for every node
* if you have new version: you will see only one request log for each device

ex: if you have 10 device nodes on the same device (whatever the property), then you should only see one request log for this device.

with docker, you can change logger in `/data/settings.js` (near to line 284)

> Also, are there any specific tests you would like done? If not, I'll just try to set it up how I would normally use it. So far everything is working with no issues - 

That's exactly what I want you to do, random/normal usage :+1: 

> which is why I wonder if I'm on the new version or not.... LOL

Hehe, it's the expected behavior :sweat_smile:

**Comment by Botched1** [comment]
> You need to change the logger to debug

Ah, yes. Of course. OK I am using the correct version. So far no issues on the device and command noides.

**Comment by Botched1** [comment]
I do notice an issue on occasion when rebooting the hub. When rebooting the hub sometimes all devices go to "Uniitialized", and stay that way even after the systemStart event comes in.

Node-red log:
image

**Comment by Botched1** [comment]
Ah, I figured out what was happening in the previous post. I did a flow download while the hubitat hub was being reboot. So the device nodes all went uninitialized because the hub could not be reached.

I assume in this scenario the systemStart does not trigger a re-initialization? Could it?

**Comment by Botched1** [comment]
Typo in event node description:
image

**Comment by fblackburn1** [comment]
> Looking at the Maker API logs it looks like when you restart the flows you get a listDevices, a findDevice, and a deviceItem event for each device in use (I am currently testing on 4 devices, so I get 4 of each of those on restart).

Oh yes you're right, I don't know what these events mean, but one request to Maker API trigger these three events in the HE log :man_shrugging: 

>Ah, I figured out what was happening in the previous post. I did a flow download while the hubitat hub was being reboot. So the device nodes all went uninitialized because the hub could not be reached.

Ah ok, nice test :+1: 

>Apparently in this scenario the systemStart event does not trigger a re-initialization. Could it?

Yes in theory, but some race condition can happened. Can you make another test (restarting HE and while restarting, changing value of a device), then check if NR receive and fix value?

**Comment by Botched1** [comment]
> Can you make another test (restarting HE and while restarting, changing value of a device), then check if NR receive and fix value? This kind of test is hazardous to do remotely

I'm not sure I follow. I can't change a device value in HE if the HE hub is rebooting? Or do you mean, reboot - download to NR during reboot - then try to change device value after HE hub is done rebooting?

**Comment by fblackburn1** [comment]
> > Can you make another test (restarting HE and while restarting, changing value of a device), then check if NR receive and fix value? This kind of test is hazardous to do remotely
> 
> I'm not sure I follow. I can't change a device value in HE if the HE hub is rebooting?
> 
> Or do you mean, reboot HE - download to NR during reboot to cause the issue - then try to change device value after HE hub is done rebooting?

Oups sorry, what I said didn't make sense :sweat_smile: 

* have a NR and HE synced
* desync your NR and HE
    * modify the webhook path in HE config with a wrong path
    * change a state of one a device
    * re-update the webhook path in HE config (with the good one)
* restart your HE

**Comment by Botched1** [comment]
OK, trying that now.

**Comment by fblackburn1** [comment]
> EDIT: If I do this:
    Reboot HE
    Do download / flow restart in Node-Red while HE is rebooting - causing device nodes to go to uninitialized
    After HE reboot is complete, change device values
    The device nodes stay Uninitialized forever (until the flow is reloaded)
Again, this is only on the device node - command and event nodes work as expected after the HE reboot is complete with no additional user action.

Good to know, I never tested this scenario

>OK, trying that now.
Be sure to have my last commit and restarted NR

**Comment by Botched1** [comment]
> Be sure to have my last commit and restarted NR

Oops. I had not done that. I'll go do that next.

**Comment by fblackburn1** [comment]
Ok, thank you for the detailed info, I'll improve my setup to reproduce it and I will come back with a fix

**Comment by fblackburn1** [comment]
@Botched1 you can retest it
To be sure you have the last commit, the version of the palette should be:
Screenshot from 2020-08-20 14-06-41
I'll fix unit tests tonigh

**Comment by Botched1** [comment]
> @Botched1 you can retest it
> To be sure you have the last commit, the palette version should be:
> Screenshot from 2020-08-20 14-06-41
> ~I'll fix unit tests tonight~ fixed

Nice job. I can confirm that:
* the device nodes update correctly after a HE hub reboot now.
* the device nodes go from uninitialized to working correctly after the HE hub reboot as well

👍

**Pull request merged**
