### PR TITLE
Dynamic device devideid

### PR DESCRIPTION
**Pull request by fblackburn1**
Allow to overwrite deviceId

Which feedback I would like:

* It works as expected?
* Unfortunately, I don't have enough devices to make a real benchmark. If someone want to do some tests, I would like to know:
    * How many devices you have on HE
    * How many devices are authorized/exposed to Maker API
    * How many device nodes you have on NR
    * How many unique device nodes you have on NR
    * How much time it takes to initialize with v1.3.3 of this plugin
    * How much time it takes to initialize with this PR

### CODE REVIEW

**Comment by Botched1** [comment]
I was going to install this and try it out, but I cannot get this version to install no matter what I do.

I did:
git clone https://github.com/fblackburn1/node-red-contrib-hubitat.git
cd node-red-contrib-hubitat
git checkout dynamic-device-deviceid

But I get: 
error: pathspec 'dynamic-device-deviceid' did not match any file(s) known to git

I'm sure it is just something stupid I'm doing wrong?

**Comment by fblackburn1** [comment]
> I was going to install this and try it out, but I cannot get this version to install no matter what I do.
> 
> I did:
> git clone https://github.com/fblackburn1/node-red-contrib-hubitat.git
> cd node-red-contrib-hubitat
> git checkout dynamic-device-deviceid
> 
> But I get:
> error: pathspec 'dynamic-device-deviceid' did not match any file(s) known to git
> 
> I'm sure it is just something stupid I'm doing wrong?

oups, my fault I make a typo in the device word: `devideid` :flushed:

**Comment by fblackburn1** [comment]
>     * Unfortunately, I don't have enough devices to make a real benchmark. If someone want to do some tests

## Without this PR
On master, each different device trigger one request. 

### Process
* Simulate the number of device by sending the same request many time.
    * Note: result may be wrong since HE can cache the response
* command: `ab -nX -c4 "http://<ip>/apps/api/<id>/devices/1?access_token=..."`

### Results
25 devices / 4 simultaneous requests = 500-600 ms
50 devices / 4 simultaneous requests  = 800-900 ms
75 devices / 4 simultaneous requests  = 1200-1500ms
100 devices / 4 simultaneous requests = 1600-2000ms

## With this PR

### Process
* 6 physical devices / 21 virtual devices
* taking the mean of the 100 sequential requests
* command: `ab -n100 -c1 "http://<ip>/apps/api/<id>/devices/1?access_token=..."

### Results
7 devices = 120 ms
27 devices = 150 ms

## Conclusion
I'll stop to bother me with performance thing, the difference range is not enough to continue to investigate :rofl:

**Comment by Botched1** [comment]
I installed this version. I didn't have a lot of time to test, but specifying a deviceId on a device node did work as expected.

Note that in its current form you have to specify a device in the node setup, or you can't save the flow. That is different than the command node where you don't have to specify a device at all.

**Comment by Botched1** [comment]
Also note that if you allow the user to not specify a device in the node configuration, you will need to ensure that "send events" is unchecked/disabled when there is no device specified. Probably obvious, but I thought I would mention it.

**Comment by fblackburn1** [comment]
> Note that in its current form you have to specify a device in the node setup, or you can't save the flow. That is different than the command node where you don't have to specify a device at all in the node config.

Oh you probably clone before my last update (and I force pushed it), you can  `git reset --hard origin/dynamic-device-devideid` or reclone the repo

> Also note that if you allow the user to not specify a device in the node configuration, you will need to ensure that "send events" is unchecked/disabled when there is no device specified. Probably obvious, but I thought I would mention it.

Oh I disabled to code to send events, but not disabled the UI checkbox :+1:
I will rework a little bit the UX (disable attribute dropdown, rename All to N/A) and disable checkbox, and push another version

**Pull request merged**
