### PR TITLE
do not always send command

### PR DESCRIPTION
**Pull request by fblackburn1**
Allow to halt command if the device state is already in given state
halt-command

### CODE REVIEW

**Comment by fblackburn1** [comment]
@Botched1 Do you think you can test it when you will have time?
Any suggestion to improve it? Does it solve your request :smiley: 

Setup
```
git clone https://github.com/fblackburn1/node-red-contrib-hubitat.git /tmp/nr-he
cd /tmp/nr-he
git checkout halt-command
docker run --name nodered-hubitat --rm -v /tmp/nr-he:/tmp/nr-he -d -p 1880:1880 nodered/node-red
docker exec -it nodered-hubitat bash
    npm install /tmp/nr-he
docker restart nodered-hubitat
```

**Comment by Botched1** [comment]
I missed this one too! Sorry.

Yes, I should be able to test later today or tomorrow. Just have remind myself how to install the non-production version. haha

**Comment by Botched1** [comment]
Doesn't seem to work.

image

Every time I click the msg.arguments=50 inject node, even when level already =50 I still see the command in maker api:
image

**Comment by Botched1** [comment]
Doesn't seem to work with switch on/off either. I get a maker api "on" command every time I hit the inject node.

image
image

**Comment by Botched1** [comment]
Ahh... But this does work. So I guess it doesn't work if you specify msg.command or msg.arguments in the incoming msg, but it does if you specify everything in the node.

Also, not sure if this is possible, but it would be vERY handy to be bale to specify "do not do command if specified attribute = command argument". Example, on a dimmer device a user sets various level% using msg.arguments input. It would be nice to say, do not send if level=msg.arguments.

**Comment by fblackburn1** [comment]
Oh I rename a lot of time some variables ... miss one :sweat_smile: 
But there is also an issue with non-string attribute value. I will make some refactor and fix it.
Thanks :+1: 

> Also, not sure if this is possible, but it would be very useful to be able to specify "do not do command if specified attribute = command argument". Example, on a dimmer device a user sets various level% using msg.arguments input. It would be nice to say, do not send if level=msg.arguments.

Well if you leave the attribute empty (in the fixed version), then it will fallback to the argument (taken from input or the configured one)

**Comment by fblackburn1** [comment]
Oh ... Maybe I was too naive in the approach.
To know if the command should be sent or not, we need to simulate the command sent to know the future attribute value.
After the simulation, we can compare the future-attribute to the configured in the node :scream: 
It may be possible for some commands, but cannot be enough generic for all

**Comment by fblackburn1** [comment]
First sorry, for having you tested an incomplete branch.
Then now it should work with and without message properties
Do not hesitate to improve documentation about halt message. I passed too much time on it. I cannot describe them for someone that use them for the first time :sweat_smile:

Limitation: currently the only way to know if command is sent or not (halted), is to check `msg.response`, but once merged, I will include it on https://github.com/fblackburn1/node-red-contrib-hubitat/issues/89

**Comment by Botched1** [comment]
A little better, but a few steps backwards.

If the command IS specified, I can't seem to change the comparison value now. See pic below - obviously there is no "on" for "level:.. But I may not want to send the ON command if level=50% for instance. 

image

**Comment by Botched1** [comment]
I don't understand the changes. Why is the highlighted part there now? Why is it necessary? I can't think of any scenario where I would want to specify both the command AND a attribute/value. Is there some use case that needed that?

image

**Comment by fblackburn1** [comment]
This message is a bit long, but since it's not simple to exaplin, I will try different examples and wording :sweat_smile: 

I will take your screenshot as example
```
command: setLevel
arguments: <defined by msg.arguments>
haltCommand: setLevel
haltCommandArgs: **must be defined**
haltAttribute: level
haltAttributeValue: 50
```
To know if the command is halted or not, the node need to define if the command sent is the same thing than the attribute value.
If `msg.arguments = 50,10`, the node needs to know how to convert `50,10`(str) to `50`(int) and compare it to `haltAttributeValue`.

It may be more obviously with `setColor` command. Its arguments can be `{"hue":88,"saturation":50,"level":90}` or `{"hex":"15fe21"}`.
It would require an hardcoded logic for each command and possible arguments number

## Static command and arguments
When command and arguments are configured, then haltCommand/haltCommandArgs are irrelevant, since we suppose that command will set the device with the haltAttribute/Value configured. Then we can make this simple logic:
```
IF haltAttributeValue == device[haltAttribute].value
THEN HALT command
```

## Dynamic arguments
When command is configured, but arguments is taken from message, then haltCommand is irrelevant, but arguments must be defined to know when to sent or not command:
```
IF haltAttributeValue == device[haltAttribute].value
AND haltCommandArgs == commandArgs
THEN HALT command
```
Otherwise we will need to hardcode and to know mappingbetween each argument and attribute value (ex: `setLevel: 50,10` --> `50`, `setColor: {"hex":"15fe21"}` --> `hue:88` ).
In the case, we cannot only check the device attribute value because the command argument can change and that's what will tell us if we should halt or not

## Dynamic command and arguments

Well since we don't interpret command and/or arguments, we must know which command will map to which attribute and which arguments will match to which value:
```
IF haltAttributeValue == device[haltAttribute].value
AND haltCommandArgs == commandArgs
AND haltCommand == command
THEN HALT command
```

## Summary
We don't want (or we can't) to map each command/argument to each attribute/value, because there is more than 90 properties/attributes and probably more custom implementation/driver specific command/attribute. For this case the halt feature need to know which command/arguments would trigger which attribute/value and then halt or not according the current device state and command received.

**Note**: We will need to find an explanation or example to add to the documentation. Because if the feature is not intuitive, maybe it's not worth it

**Comment by Botched1** [comment]
"To know if the command is halted or not, the node need to define if the command sent is the same thing as the attribute value."

I guess that is where I disagree. I think the design would have been fine with just evaluating the current attribute and value, then sending the command or not. No mapping at all.

The only scenarios that doesn't work well in, that I can think of, is for commands that take a compound argument, and the attribute to compare to is a simple value.

For all of the common commands it should work well - setLevel vs level, on/off vs switch value on/off, etc.

**Comment by fblackburn1** [comment]
> "To know if the command is halted or not, the node need to define if the command sent is the same thing as the attribute value."
> 
> I guess that is where I disagree. I think the design would have been fine with just evaluating the current attribute and value, then sending the command or not. No mapping at all.
> 

Yes it should work for the majority of commands, but I can already hear about supporting every other corner cases.

> The only scenarios that doesn't work well in, that I can think of, is for commands that take a compound argument, and the attribute to compare to is a simple value.
> 
> For all of the common commands it should work well - setLevel vs level, on/off vs switch value on/off, etc.
> 

There is still some corner cases, example auto convert command argument to integer or capital letter for command argument but not attribute value.
Trying to do the minimal thing, will leave up to grow as a big mapping (well it's my fear) 

> With the complexity in how it is done in the current test version, I would likely just leave the feature off and handle it in a switch node manually like I do today. And that's ok - you don't make the nodes just for me. If you and/or others prefer the more complex version that covers more use cases, that's OK too. :)

I agree, I think I will leave it in standby for now

**Comment by Botched1** [comment]
I think that makes sense. It needs more thought.

The complexity involved is likely more work than the feature is worth.

**Comment by Botched1** [comment]
Now that I have implemented this behavior in subflows in node-red (for a subset of commands/attributes), I am now convinced this **should not** be done in the hubitat command node. 

There are simply too many custom commands that would have to be manually coded in for this to be worth it. It would be a support nightmare. As such I think this should feature request be abandoned.

I once the command node publishes msg.requerstCommand/requestArguments I will post my subflow that handles this to the forum, and them people can add to it/manually add the command/attribute pairs they need if this is a feature they want.

**Pull request closed without merging**
