### PR TITLE
Pull request for return-request-command

### PR DESCRIPTION
**Pull request by fblackburn1**
This PR add properties to command node. Now it output `requestCommand` and `requestArguments` with the value sent to the server

### CODE REVIEW

**Comment by fblackburn1** [comment]
@Botched1 Does it look like you want? Did you have some corner case in your head about this feature?

**Comment by Botched1** [comment]
Yes, this would work well I think! It would allow for creation of generic subflows to check device node value vs requested command.

**Comment by fblackburn1** [comment]
> For instance, today in my validation subflow I HAVE TO specify msg.command/msg.arguments to the comnmand node (instead of using the node configuration) so that I have a msg.command and msg.arguments to look at in the command node output. This change would allow me to go back using pre-configured nodes (and remove a lot of change nodes).

And after all your tests, do you still consider that output:
*  `msg.requestCommand`
*  `msg.requestArguments`
is needed to be different than input:
*  `msg.command`
*  `msg.arguments`

I don't have a strong opinion about it, but your deleted comment made me hesitate
My concern is only to avoid confuse people and I'm a too technical guy to know the answer :laughing:

**Comment by Botched1** [comment]
> * `msg.requestCommand`
> * `msg.requestArguments`

To not break anyone's existing flows, the output from the command node should not use msg.command/msg.arguments.

I think you had the right idea by putting them in msg.requestCommnd/msg.requestArguments.

**Pull request merged**
